name: Site Deploy
on:
  push:
    branches:
      - main
    paths:
      - "apps/site/**"
      - ".github/workflows/site-deploy.yml"
      - "package.json"
      - "lerna.json"
      - "package-lock.json"

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Split the commands and add error handling
      - name: Install dependencies
        run: npm i

      - name: Build site
        run: npm run site:build

      - name: List directory contents
        run: ls -la

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./apps/site/build/
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
