name: Site Deploy
on:
  push:
    branches:
      - main
    paths:
      - "apps/site/**" # Only trigger when changes occur in apps/site directory

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i && npm run site:build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./apps/site/build/
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
