name: Site Deploy
on:
  push:
    branches:
      - main
    paths:
      - "apps/site/**"
      - ".github/workflows/site-deploy.yml"
      - "package.json"
      - "lerna.json"
      - "package-lock.json"

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i && npm run site:build && ls -la
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./apps/site/build/
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
